### ISSUE TITLE
license information

### ISSUE THREAD

**Issue by trebmuh** [jake-g/pitch_shift#2]
Hi @jake-g , I can't find a license information. Could please you clarify that?

**Comment by jake-g** [comment]
Thanks for asking! Added a license also dont use this to cheat in school!

**Comment by trebmuh** [comment]
Thanks @jake-g .
Is that intended you put the license file in a different branch than master?

**Comment by jake-g** [comment]
thanks for the heads up i didnt realize using github online to add the file also created another branch. Ill just merge it to master

**Comment by trebmuh** [comment]
👍
